---
title: "BIOST 79 Figures"
author: "Gabby Lopez"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(rigr)
library(ggplot2)
library(gtsummary)
library(gapminder)
```


```{r}
hcbc <- read_csv('HCBC_2015_ClusterData_Observations.csv')
hcbc <- hcbc %>%
  mutate(PropAffected_mean = PctAffected_mean / 100)

hcbc <- hcbc %>% mutate(Prop_LiveCoral = PercentLiveCoralCover_mean / 100) %>%
  mutate(LiveCoral = Prop_LiveCoral * AreaSurveyed_m2_sum) %>%
  mutate(Affected = PropAffected_mean * LiveCoral) %>% 
  mutate(LiveCoral = round(LiveCoral)) %>% 
  filter(LiveCoral > 0) %>% 
  mutate(Affected = round(Affected))

summary(hcbc)

my_theme <-
  list(
    "tbl_summary-str:default_con_type" = "continuous2",
    "tbl_summary-str:continuous_stat" = c(
      "{median} ({p25} - {p75})",
      "{mean} ({sd})",
      "{min} - {max}"
    ),
    "style_number-arg:big.mark" = "",
    "tbl_summary-fn:percent_fun" = function(x) style_percent(x, digits = 3)
  )
gtsummary::set_gtsummary_theme(my_theme)

hcbc %>%  select(c('Island_Name','Depth_m_mn','AreaSurveyed_m2_sum','LiveCoral','PctAffected_mean','PctCoralPartialBleached_mean','PctCoralFullyBleached_mean','Prop_BleachResTaxa')) %>%
  gtsummary::tbl_summary(
    by = Island_Name, 
    include=c(Depth_m_mn, AreaSurveyed_m2_sum, LiveCoral, PctAffected_mean, PctCoralPartialBleached_mean, PctCoralFullyBleached_mean, Prop_BleachResTaxa),
    list(
      Depth_m_mn ~ 'Bathymetric Depth (m)',
      AreaSurveyed_m2_sum ~ 'Area Surveyed (m2)',
      LiveCoral ~ 'Live Coral Cover (m)',
      PctAffected_mean ~ 'Percent Bleached',
      PctCoralPartialBleached_mean ~ 'Percent Partially Bleached',
      PctCoralFullyBleached_mean ~ 'Percent Fully Bleached',
      Prop_BleachResTaxa ~ 'Proportion of Bleach Resistant Taxa'
    ),
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c(
      "{median} ({min}, {max})"
    )
  ) %>%
  add_n() %>%
  bold_labels() %>%
  modify_header(label ~ "**Island**")

hcbc %>%  select(c('Depth_m_mn','AreaSurveyed_m2_sum','LiveCoral','PctAffected_mean','PctCoralPartialBleached_mean','PctCoralFullyBleached_mean','Prop_BleachResTaxa')) %>%
  gtsummary::tbl_summary(
    include=everything(),
    label=list(
      Depth_m_mn ~ 'Bathymetric Depth (m)',
      AreaSurveyed_m2_sum ~ 'Area Surveyed (m2)',
      LiveCoral ~ 'Live Coral Cover (m)',
      PctAffected_mean ~ 'Percent Bleached',
      PctCoralPartialBleached_mean ~ 'Percent Partially Bleached',
      PctCoralFullyBleached_mean ~ 'Percent Fully Bleached',
      Prop_BleachResTaxa ~ 'Proportion of Bleach Resistant Taxa'
    ),
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c(
      "{median} ({min}, {max})"
    )
  ) %>%
  add_n() %>%
  bold_labels()
  
hcbc %>%  select(c('Island_Name','Depth_m_mn','AreaSurveyed_m2_sum','LiveCoral','PctAffected_mean','PctCoralPartialBleached_mean','PctCoralFullyBleached_mean','Prop_BleachResTaxa','DHW.MeanMax_Degree_Heating_Weeks_MO03','DHW.MeanMax_Degree_Heating_Weeks_YR10YR01','mean_weekly_range_SST_CRW_Daily_ALLB4','LBSP_AgGolf_runoff_01_sc','LBSP_Urban_runoff_01_sc','TourRec_DirectHuman_10yrAvgPUD','mean_PAR_MODIS_Daily_MO03')) %>%
  gtsummary::tbl_summary(
    by = Island_Name, 
    include=c(Depth_m_mn, AreaSurveyed_m2_sum, LiveCoral, PctAffected_mean, PctCoralPartialBleached_mean, PctCoralFullyBleached_mean, Prop_BleachResTaxa,DHW.MeanMax_Degree_Heating_Weeks_MO03,DHW.MeanMax_Degree_Heating_Weeks_YR10YR01,mean_weekly_range_SST_CRW_Daily_ALLB4,LBSP_AgGolf_runoff_01_sc,LBSP_Urban_runoff_01_sc,TourRec_DirectHuman_10yrAvgPUD,mean_PAR_MODIS_Daily_MO03),
    list(
      Depth_m_mn ~ 'Bathymetric Depth (m)',
      AreaSurveyed_m2_sum ~ 'Area Surveyed (m2)',
      LiveCoral ~ 'Live Coral Cover (m)',
      PctAffected_mean ~ 'Percent Bleached',
      PctCoralPartialBleached_mean ~ 'Percent Partially Bleached',
      PctCoralFullyBleached_mean ~ 'Percent Fully Bleached',
      Prop_BleachResTaxa ~ 'Proportion of Bleach Resistant Taxa',
      DHW.MeanMax_Degree_Heating_Weeks_MO03 ~ 'DHW (3 months)',
      DHW.MeanMax_Degree_Heating_Weeks_YR10YR01 ~ 'DHW (10 years)',
      mean_weekly_range_SST_CRW_Daily_ALLB4 ~ 'Mean Weekly SST Range (C)',
      LBSP_AgGolf_runoff_01_sc ~ 'Agricultural Runoff',
      LBSP_Urban_runoff_01_sc ~ 'Urban Runoff',
      TourRec_DirectHuman_10yrAvgPUD ~ 'Tourism (10 years)',
      mean_PAR_MODIS_Daily_MO03 ~ 'PAR level'
    ),
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c(
      "{median} ({min}, {max})"
    )
  ) %>%
  add_n() %>%
  bold_labels() %>%
  modify_header(label ~ "**Island**")
```

Thermal Stress

```{r pressure, echo=FALSE}
reg1 <- glm(Affected ~ DHW.MeanMax_Degree_Heating_Weeks_MO03 + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01 + mean_weekly_range_SST_CRW_Daily_ALLB4 + DHW.MeanMax_Degree_Heating_Weeks_MO03:Prop_BleachResTaxa + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01:Prop_BleachResTaxa + mean_weekly_range_SST_CRW_Daily_ALLB4:Prop_BleachResTaxa,
            family = poisson,
            data = hcbc,
            offset = log(LiveCoral))
reg1

reg2 <- regress("rate", Affected ~ DHW.MeanMax_Degree_Heating_Weeks_MO03 + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01 + mean_weekly_range_SST_CRW_Daily_ALLB4 + DHW.MeanMax_Degree_Heating_Weeks_MO03:Prop_BleachResTaxa + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01:Prop_BleachResTaxa + mean_weekly_range_SST_CRW_Daily_ALLB4:Prop_BleachResTaxa +
DHW.MeanMax_Degree_Heating_Weeks_MO03:Depth_m_mn + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01:Depth_m_mn + mean_weekly_range_SST_CRW_Daily_ALLB4:Depth_m_mn,
                data = hcbc,
                offset = log(LiveCoral))
reg2

reg02 <- regress("rate", Affected ~ DHW.MeanMax_Degree_Heating_Weeks_MO03 + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01 + mean_weekly_range_SST_CRW_Daily_ALLB4 + DHW.MeanMax_Degree_Heating_Weeks_MO03:Prop_BleachResTaxa + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01:Prop_BleachResTaxa + mean_weekly_range_SST_CRW_Daily_ALLB4:Prop_BleachResTaxa +
DHW.MeanMax_Degree_Heating_Weeks_MO03:DepthBin_5m + DHW.MeanMax_Degree_Heating_Weeks_YR10YR01:DepthBin_5m + mean_weekly_range_SST_CRW_Daily_ALLB4:DepthBin_5m,
                data = hcbc,
                offset = log(LiveCoral))
reg02
```

Human Activity
```{r}
reg3 <- regress("rate", Affected ~ LBSP_AgGolf_runoff_01_sc + LBSP_Urban_runoff_01_sc + TourRec_DirectHuman_10yrAvgPUD + LBSP_AgGolf_runoff_01_sc:Prop_BleachResTaxa + LBSP_Urban_runoff_01_sc:Prop_BleachResTaxa + TourRec_DirectHuman_10yrAvgPUD:Prop_BleachResTaxa +
LBSP_AgGolf_runoff_01_sc:Depth_m_mn + LBSP_Urban_runoff_01_sc:Depth_m_mn + TourRec_DirectHuman_10yrAvgPUD:Depth_m_mn,
                data = hcbc,
                offset = log(LiveCoral))
reg3

reg03 <- regress("rate", Affected ~ LBSP_AgGolf_runoff_01_sc + LBSP_Urban_runoff_01_sc + TourRec_DirectHuman_10yrAvgPUD + LBSP_AgGolf_runoff_01_sc:Prop_BleachResTaxa + LBSP_Urban_runoff_01_sc:Prop_BleachResTaxa + TourRec_DirectHuman_10yrAvgPUD:Prop_BleachResTaxa +
LBSP_AgGolf_runoff_01_sc:DepthBin_5m + LBSP_Urban_runoff_01_sc:DepthBin_5m + TourRec_DirectHuman_10yrAvgPUD:DepthBin_5m,
                data = hcbc,
                offset = log(LiveCoral))
reg03
```

PAR
```{r}
reg4 <- regress("rate", Affected ~ mean_PAR_MODIS_Daily_MO03 + mean_PAR_MODIS_Daily_MO03:Prop_BleachResTaxa + mean_PAR_MODIS_Daily_MO03:Depth_m_mn,
                data = hcbc,
                offset = log(LiveCoral))
reg4

reg04 <- regress("rate", Affected ~ mean_PAR_MODIS_Daily_MO03 + mean_PAR_MODIS_Daily_MO03:Prop_BleachResTaxa + mean_PAR_MODIS_Daily_MO03:DepthBin_5m,
                data = hcbc,
                offset = log(LiveCoral))
reg04
```

Location
```{r}
reg5 <- regress("rate", Affected ~ Island_Name + Island_Name:Prop_BleachResTaxa + Island_Name:Depth_m_mn,
                data = hcbc,
                offset = log(LiveCoral))
reg5
```

```{r eval=FALSE, include=FALSE}
thermal %>% ggplot(aes(x = DHW.MeanMax_Degree_Heating_Weeks_MO03, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point() 
thermal %>% ggplot(aes(x = mean_weekly_range_SST_CRW_Daily_ALLB4, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point() 

human %>% ggplot(aes(x = LBSP_AgGolf_runoff_01_sc, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point()
human %>% ggplot(aes(x = LBSP_Urban_runoff_01_sc, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point()
human %>% ggplot(aes(x = TourRec_DirectHuman_10yrAvgPUD, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point()

par %>% ggplot(aes(x = mean_PAR_MODIS_Daily_MO03, y = PctAffected_mean, col = factor(DepthBin_5m))) + geom_point() + labs(x='Mean Daily PAR (umol/sec)', y='Percent of Bleached Coral (%)', main='PAR levels and Percentage of Bleached Coral by Bathymetric Depth') + scale_colour_discrete(name='Bathymetric Depth (m)', breaks=c("[0,5]","(5,10]","(10,15]"), labels=c("<= 5","> 5 and <= 10","> 10 and <= 15")) + geom_jitter()
par %>% ggplot(aes(x = mean_PAR_MODIS_Daily_MO03, y = PropAffected_mean, col = Prop_BleachResTaxa)) + geom_point(aes(shape=factor(DepthBin_5m)))
```

